version: '3.7'

services:
  postgresql-db:
    container_name: cw6_server_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cw6